apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5434
    database: homeassistant_rag
    user: raguser
    secureJsonData:
      password: ragpass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
